version: "3.8"

services:
  php:
    container_name: slim_php
    build:
      context: ./docker/php
    environment:
      JWT_SECRET: C3ntip3d32199
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/slim_app

  nginx:
    container_name: slim_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/slim_app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P0stGr3s4dm!n
      POSTGRES_DB: usapopulation
    volumes:
       - ./docker/postgresql/data:/var/lib/postgresql/data

